version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - corepack enable
      - yarn install --frozen-lockfile

  build:
    commands:
      - echo Installing dependencies ...
      - yarn build

artifacts:
  base-directory: dist
  files:
    - "**/*"

cache:
  paths:
    - node_modules/**/*
